### ISSUE TITLE
Add bike shops and stadiums to map

### ISSUE THREAD

**Issue by leonardehrenfried** [buskerudbyen/proposal-visualizer#1]

**Comment by leonardehrenfried** [comment]
"Some more details should be added to the base map: 
Sports stadiums - Like: https://www.openstreetmap.org/#map=18/59.73440/10.20162&layers=C 
Bike shops - Like: https://www.openstreetmap.org/#map=20/59.73817/10.20178&layers=C "

**Comment by Beck-berry** [comment]
This is the backend task for [#17](https://github.com/buskerudbyen/cycling-norway/issues/17)

**Comment by Beck-berry** [comment]
It is not quite obvious for me how we should visualize the stadiums based on the example. Is it enough to write the names onto the map? When `leisure` is `stadium` or `pitch`?

And for the bike shops, should we go with the yellow background bike icon, right? (When `shop == bicycle`?)

**Comment by leonardehrenfried** [comment]
For the stadium, could  you try using something like this: https://icons8.com/icon/JlLTMd4NfTIp/stadium

It's often not easy to predict how an icon will look when it's quite small in the map so you might need to experiment with others.

**Comment by leonardehrenfried** [comment]
Actually, I realised that I like another icon website better: https://thenounproject.com/icon/stadium-1340141/

**Comment by leonardehrenfried** [comment]
I have pro account and will send you the login data.
